In [1]:
%config InlineBackend.figure_format = 'retina'
%matplotlib inline

import numpy as np
import pandas as pd

cepheids_df = pd.read_csv('./data/big_cepheids_table.csv')

## Solution: Calculate the distance to each star

First define a function to convert from parallax to distance. Remember the input values will be in mas, and the formula needs arcsec:

In [2]:
def parallax_to_distance(parallax_mas):
    parallax_arcsec = parallax_mas * 1e-3
    distance = 1./parallax_arcsec
    return(distance)

Now use this to get the distance of each star:

In [3]:
cepheids_df['distance_pc'] = parallax_to_distance(cepheids_df['parallax_mas'])

In [4]:
cepheids_df

,Star_ID,parallax_mas,logP,mag_B,err_B,mag_V,err_V,mag_I,err_I,E_B_V,A_V,distance_pc
0,XX Cen,0.564,1.040,8.882,0.019,7.855,0.012,6.754,0.008,0.5223,1.6191,1773.049645
1,T Mon,0.733,1.432,7.436,0.022,6.187,0.014,5.005,0.010,0.5997,1.8590,1364.256480
2,TW Nor,0.362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2762.430939
3,CV Mon,0.602,0.731,11.681,0.015,10.314,0.010,8.653,0.006,1.4373,4.4556,1661.129568
4,RY Sco,0.754,1.308,9.568,0.018,8.037,0.012,6.271,0.008,1.2228,3.7907,1326.259947
...,...,...,...,...,...,...,...,...,...,...,...,...
62,delta Cep,3.556,0.730,4.684,0.018,3.990,0.012,NaN,NaN,1.4914,4.6233,281.214848
63,U Aql,1.748,0.847,7.536,0.016,6.457,0.011,5.279,0.007,0.3334,1.0337,572.082380
64,eta Aql,3.674,0.856,4.744,0.017,3.918,0.011,3.036,0.007,0.1936,0.6001,272.182907
65,RT Aur,1.841,0.571,6.120,0.017,5.487,0.011,4.822,0.006,0.1844,0.5717,543.183053
66,SU Cru,0.211,1.109,11.613,0.015,9.802,0.008,7.658,0.003,NaN,NaN,4739.336493

Remember, always have a quick look at your data every time you run a function on it. It's good practice to check it's worked as expected before moving on to the next step.

[back to the worksheets](ex-parallax-dist)